apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  selector:
    matchLabels:
      app: jupyter
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - name: jupyter
        image: jupyter/base-notebook:notebook-6.0.3
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.password=''", "--NotebookApp.token=''"]
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
spec:
  ports:
  - port: 8888
    protocol: TCP
  selector:
    app: jupyter
  type: LoadBalancer  
