# this is workflow to build and test kubernetes application deployment
name: ci-kube

on: [push]

jobs:
  Build:
    name: ci-kube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.0.0
        with:
          minikube version: 'v1.9.2'
          kubernetes version: 'v1.18.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Interact with the cluster
        run: kubectl get nodes
      - name: Apply deployment
        run: kubectl apply -f deployment.yaml
      - name: Apply service
        run: kubectl apply -f jupyter-svc.yaml
  #    - name: Test Service
  #      run: curl --connect-timeout 3 -I $(minikube service jupyter --url)
        
